name: "Netlify Deploy [Production]"

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js 14.15.5
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5
      - run: npm run setup:frontend
      - run: npm run build:frontend --if-present
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
